[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# 编译器配置
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# 测试网配置
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
goerli = "${GOERLI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]

goerli = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

